### ISSUE TITLE
IPC Request

### ISSUE THREAD

**Issue by Limiana** [apetih/rtyping#1]
Hello! I would like to integrate this plugin with XIVInstantMessenger: https://github.com/NightmareXIV/XIVInstantMessenger
Easiest way would be to add an IPC function that will allow other plugins to register their own function which would tell your plugin whether typing is happening, and then query them in this function https://github.com/apetih/rtyping/blob/main/client/rtyping/Windows/PartyTypingUI.cs#L153
Please let me know whether you would agree to add this and whether you would like to have a PR at a later time with implementation of this function.

**Comment by apetih** [comment]
Hello!
I'm perfectly okay with adding said integration! It sounds pretty neat!
The only issue at present is that I am quite new to the development of Dalamud Plugins, so I currently lack the knowledge of how to add or use IPC, and as such any help or assistance with it would be greatly appreciated.

**Comment by Limiana** [comment]
Nice, thanks for accepting the idea. I will be able to do a PR for it in some time.
